---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
bases:
  - ../../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
resources:
  - service-dashboard.yaml
