---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base
  - ingressroute.yaml
  - dashboard-service.yaml
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
