---
kind: Daemonset
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
spec:
  template:
    spec:
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: traefik
          args:
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetescrd
            - --providers.kubernetescrd.allowCrossNamespace=true
            - --serverstransport.insecureskipverify=true
            - --api.dashboard=true
            - --api.insecure=true
            ###- --certificatesresolvers.myresolver.acme.tlschallenge
            ###- --certificatesresolvers.myresolver.acme.email=jay.amorin@gmail.com
            ###- --certificatesresolvers.myresolver.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            ###- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            - --log.level=DEBUG
          ports:
            - name: dashboard
              containerPort: 8080

