---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base
  - dashboard-service.yaml
  - traefik-ingress-controller-dashboard-ingressroute.yaml
patches:
  - path: daemonset.yaml
