---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-to-https-middleware.yaml
  - basic-authentication-middleware.yaml
  - dashboard-service.yaml
  - traefik-ingress-controller-dashboard-ingressroute.yaml
  - kubernetes-dashboard-ingressroute.yaml
patches:
  - path: daemonset.yaml
