---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base
  - dashboard-service.yaml
  - dashboard-middleware.yaml
  - dashboard-ingressroute.yaml
patches:
  - path: deployment.yaml
  - path: service.yaml
