---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.kubernetescrd
            #- --certificatesresolvers.staging.acme.tlschallenge
            #- --certificatesresolvers.staging.acme.email=jay.amorin@you.com
            #- --certificatesresolvers.staging.acme.storage=/acme/staging-acme.json
            #- --certificatesresolvers.staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            #- --certificatesresolvers.prod.acme.tlschallenge
            #- --certificatesresolvers.prod.acme.email=jay.amorin@you.com
            #- --certificatesresolvers.prod.acme.storage=/acme/prod-acme.json
            #- --certificatesresolvers.prod.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
            - --api.dashboard
            - --providers.kubernetescrd.allowCrossNamespace
            - --serverstransport.insecureskipverify
            - --ping
            - --providers.http.tls.insecureskipverify
            - --log.level=DEBUG
          #volumeMounts:
          #  - mountPath: "/acme"
          #    name:: "acme"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
          securityContext:
            capabilities:
              drop:
              - ALL
              add:
              - NET_BIND_SERVICE
          #volumes:
          #  - name: acme
          #    hostPath:
          #      path: /opt/traefik/acme
