---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      nodePort: 30080
    - protocol: TCP
      name: websecure
      port: 443
      nodePort: 30443
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: ingress-controller
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  labels:
    app.kubernetes.io/name: traefik-dashboard
spec:
  ports:
    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: ingress-controller
