---
kind: Daemonset
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  labels:
    app.kubernetes.io/name: traefik-ingress-controller
    app.kubernetes.io/component: load-balancer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-ingress-controller
      app.kubernetes.io/component: load-balancer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik-ingress-controller
        app.kubernetes.io/component: load-balancer
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.7
          args:
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetescrd
            - --certificatesresolvers.myresolver.acme.tlschallenge
            - --certificatesresolvers.myresolver.acme.email=foo@you.com
            - --certificatesresolvers.myresolver.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
