---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
commonLabels:
  app.kubernetes.io/part-of: traefik-ingress-controller
resources:
  - namespace.yaml
  - kubernetes-crd-definition-v1.yml
  - kubernetes-crd-rbac.yml
  - daemonset.yaml
  - service-account.yaml
  - service.yaml
