---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app.kubernetes.io/name: traefik-ingress-controller
    app.kubernetes.io/component: load-balancer
