name: tag and release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed
  merged:

jobs:
  tests:
    uses: jayamorin/gha-workflows/.github/workflows/test-krm.yaml@develop
    if: ${{ (github.event.pull_request.types == 'opened') || (github.event.pull_request.types == 'reopened') }}

  develop:
    uses: jayamorin/gha-workflows/.github/workflows/tag-prerelease-develop.yaml@develop
    needs: tests

  main:
    uses: jayamorin/gha-workflows/.github/workflows/tag-release-main.yaml@develop
    needs: tests
