name: tag and release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ (github.event.pull_request.types == 'opened') || (github.event.pull_request.types == 'reopened') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test krm
        uses: jayamorin/gha-workflows/.github/workflows/test-krm.yaml@develop

  develop:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ (github.event.pull_request.merged == 'true') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: tag and preprelease
        uses: jayamorin/gha-workflows/.github/workflows/tag-prerelease-develop@develop

  main:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ (github.event.pull_request.merged == 'true') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: tag and release
        uses: jayamorin/gha-workflows/.github/workflows/tag-release-main.yaml@develop