name: tag and release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - ready_for_review
      - review_requested
      
jobs:
  tests:
    uses: jayamorin/gha-workflows/.github/workflows/test-krm.yaml@develop

  develop:
    uses: jayamorin/gha-workflows/.github/workflows/tag-prerelease-develop.yaml@develop
    needs: tests
    secrets: inherit

  main:
    uses: jayamorin/gha-workflows/.github/workflows/tag-release-main.yaml@develop
    needs: tests
    secrets: inherit